__title__ = 'omxplayer'
__description__ = 'A library for controlling omxplayer on the Raspberry Pi'
__author__ = 'Will Price'
__author_email__ = 'will.price94+dev@gmail.com'
__version__ = '0.3.1'
__license__ = 'LGPLv3+'
__copyright__ = 'Copyright 2018 Will Price'
